//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BLL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password and confirm password not matching.
        /// </summary>
        internal static string llce00009 {
            get {
                return ResourceManager.GetString("llce00009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input new password .
        /// </summary>
        internal static string llce00010 {
            get {
                return ResourceManager.GetString("llce00010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input confirm password.
        /// </summary>
        internal static string llce00011 {
            get {
                return ResourceManager.GetString("llce00011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password should not be same as old password.
        /// </summary>
        internal static string llce00012 {
            get {
                return ResourceManager.GetString("llce00012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is error.Please input again!.
        /// </summary>
        internal static string llce00013 {
            get {
                return ResourceManager.GetString("llce00013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password has been changed. Please login again..
        /// </summary>
        internal static string llci00001 {
            get {
                return ResourceManager.GetString("llci00001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered successfully!.
        /// </summary>
        internal static string llci00002 {
            get {
                return ResourceManager.GetString("llci00002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully!.
        /// </summary>
        internal static string llci00003 {
            get {
                return ResourceManager.GetString("llci00003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully!.
        /// </summary>
        internal static string llci00004 {
            get {
                return ResourceManager.GetString("llci00004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droped this order!.
        /// </summary>
        internal static string llci00005 {
            get {
                return ResourceManager.GetString("llci00005", resourceCulture);
            }
        }
    }
}
